theme: jekyll-theme-minimal
title: Missing Values project title
description: Short description of the project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
