theme: jekyll-theme-minimal
title: Missing Values project
description: Short description of the project
show_downloads: True
navigation:
  - title: Home
    url : index.md
  - title: Test
    url : test.md
