theme: jekyll-theme-minimal
title: Missing Values project
description: Short description of the project
show_downloads: True
navigation:
  - title: Home
    url : index
  - title: Introduction
    url : intro
  - title: Description
    url : description